#!/bin/bash

javaFile=$1
comsolPath="/Applications/COMSOL54/Multiphysics"

echo "Compiling comsolbuiler package..."
javac -d . -cp "$comsolPath/plugins/*" -source 7 -target 7 src/*
echo "Compiling "$javaFile" into "${javaFile::${#javaFile}-5}".class..."
javac -cp "$comsolPath/plugins/*":"." -source 7 -target 7 $javaFile
echo "Building comsolbuiler.jar..."
jar -cvf comsolbuilder.jar comsolbuilder/*
echo "Starting COMSOL..."
$comsolPath/bin/comsol batch -dev $PWD/comsolbuilder.jar -inputfile $PWD/${javaFile::${#javaFile}-5}.class -outputfile $PWD/${javaFile::${#javaFile}-5}.mph

echo "Completed! Removing files..."
rm -r comsolbuilder
rm ${javaFile::${#javaFile}-5}.class
rm comsolbuilder.jar
echo "Done!"
